### ISSUE TITLE
Text elements do not render correct background colors

### ISSUE THREAD

**Issue by Akin909** [bryphe/revery#57]
![revery-text-bug](https://user-images.githubusercontent.com/22454918/48675008-0abc7e80-eb4b-11e8-9051-fdbf5e8e95dc.png)

Setting a background for text elements does not set the color in the actual character's cell to match the overall background color leading to a patchy appearance, not entirely sure how to go about looking into this @bryphe, as the meat of how `revery` works aka shaders etc. is very new to me but could have a look if you point in me the right direction

**Comment by bryphe** [comment]
Nice catch @Akin909. Definitely a bug with how we render text.

The shader where we color / render the text is here: 
https://github.com/bryphe/revery/blob/c20634b72ab39dea1372aaef7d0b519452773df2/src/UI/FontShader.re#L31

The 'texture' we use to read the font has only a single channel (`t.a` is a float value from 0.0 -> 1.0). In theory - this code should work OK to make the text transparent (since it's setting the alpha value to 0), but we don't set the appropriate blend modes (which tell the GPU how to combine pixels that are already drawn with pixels that you are sending).

**Comment by bryphe** [comment]
@Akin909 - hope you don't mind - I took a go at this w/ #60.

**Comment by bryphe** [comment]
This should be fixed now, @Akin909 ! Let me know if it's not for you 👍
